version: "3.9"

services:
  web:
    container_name: web
    build:
      dockerfile: Dockerfile
      context: ./
      target: builder
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    env_file:
      - .env
    ports:
      - "5173:5173"
